language: go

addons:
  ssh_known_hosts: home199125616.1and1-data.host
  apt:
    packages:
      - sshpass
      - lftp
go:
  - master

install:
  - go get github.com/spf13/hugo

script:
  - hugo

after_success:
  "sshpass -p $RSYNC_PASSWORD lftp -u $RSYNC_USER -e 'mirror --reverse ${TRAVIS_BUILD_DIR}/public/ /beta' sftp://home199125616.1and1-data.host
notifications:
  email:
    on_failure: always
