language: go

addons:
  ssh_known_hosts: home199125616.1and1-data.host
  apt:
    packages:
      - lftp
go:
  - master

install:
  - go get github.com/spf13/hugo

script:
  - hugo -b http://longmeadow-church.org.uk/beta/

after_success:
  "lftp -u ${FTP_USER},${FTP_PASSWORD} -e 'mirror --reverse public/ /beta' sftp://home199125616.1and1-data.host"
notifications:
  email:
    on_failure: always
