language: go

addons:
  ssh_known_hosts: home199125616.1and1-data.host
  apt:
    packages:
      - sshpass
go:
  - master

install:
  - go get github.com/spf13/hugo

script:
  - hugo

after_success:
  "sshpass -p $RSYNC_PASSWORD rsync -r --delete-after --quiet public/ $RSYNC_USER@home199125616.1and1-data.host:/beta/"
notifications:
  email:
    on_failure: always
